### ISSUE TITLE
Missing API Tracker

### ISSUE THREAD

**Issue by SinZ163** [ModDota/DotaUI#20]
Note: This list is for Panorama API only and only counts if it's needed to reimplement the UI for normal Dota. Lua is not a valid solution

API Wishlist:
- [ ] Spell amplification #8
- [ ] Base Attributes, Current Attributes, Bonus Attributes #9 
- [x] Toggle Autocast status - Possible with PrepareUnitOrder https://github.com/ModDota/DotaUI/commit/89fd89158af6b7e7cff8654b7f8507d403785cae
- [ ] AbilityLayout of selected unit #12 
- [ ] Minimap Background and/or material parsing #15 
- [ ] Get current equipped hud skin #21
- [ ] Get Effigy Inscription #24 
- [ ] Get PA Gravestone info #24
- [ ] Get Glyph Cooldown
- [ ] Get Scan Cooldown
- [ ] Get Courier Tooltip (Sockets, Name, Signature) #25 
- [ ] Get Courier death time #25 
- [ ] Get Buyback Cost #26 
- [ ] Get Death Cost #26 
- [ ] Get Buyback Cooldown #26 
- [ ] Announce buyback Status #26
- [ ] Get hotkey modifiers for Items #29
- [ ] Get Selected Guide #31 
- [ ] Save Selected Guide #31
- [ ] Get Shops info for current map. #31
- [ ] Get list of items that exist #31
- [ ] Get buildup of items. #31

Event Wishlist:
- [ ] Client events for abilities going on cooldown
- [ ] Client events for abilities entering ability phase
- [ ] Client event for entering ability learn mode
- [ ] Client event for glyph being off cooldown.
- [ ] Client event for scan being off cooldown.

**Comment by Perryvw** [comment]
CSS Wishlist/Bugs:
- [ ] Bug: Black shadows (box-shadow ~~or text-shadow~~) are not possible.
- [ ] Bug: Clip: radial does not work in tools on all machines. [Sample code.](https://gist.github.com/Perryvw/d3c7c9e3dc67154ab9110c97be37a666)
- [x] Wish: `overflow: overflow` css property. --**EDIT:** This exists (undocumented) `overflow: noclip;`
